#!/bin/bash
# Starts Expo with local Supabase instance.
# Auto-detects LAN IP so Expo Go on phone can reach the local Supabase.

set -e

# Detect LAN IP (works on Linux and macOS)
LOCAL_IP=$(ip route get 1 2>/dev/null | awk '{print $7; exit}') \
  || LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null) \
  || LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}')

if [ -z "$LOCAL_IP" ]; then
  echo "ERROR: Could not detect local IP address."
  exit 1
fi

echo "Local Supabase URL: http://$LOCAL_IP:54321"

# Read local anon key from .env.local.keys (gitignored) or use the default local key
LOCAL_ANON_KEY_FILE="$(dirname "$0")/../.env.local.keys"
if [ -f "$LOCAL_ANON_KEY_FILE" ]; then
  # shellcheck disable=SC1090
  source "$LOCAL_ANON_KEY_FILE"
fi

# Fallback to default local Supabase anon key if not set
LOCAL_ANON_KEY="${SUPABASE_LOCAL_ANON_KEY:-$(npx supabase status 2>/dev/null | grep 'Publishable' | grep -oP 'sb_publishable_\S+')}"

if [ -z "$LOCAL_ANON_KEY" ]; then
  echo "ERROR: Could not find local Supabase anon key."
  echo "Run 'npx supabase start' first, then try again."
  exit 1
fi

# Write .env.local (gitignored)
cat > "$(dirname "$0")/../.env.local" <<EOF
# Auto-generated by scripts/start-local.sh — DO NOT EDIT MANUALLY
EXPO_PUBLIC_SUPABASE_URL=http://$LOCAL_IP:54321
EXPO_PUBLIC_SUPABASE_ANON_KEY=$LOCAL_ANON_KEY
EOF

echo ".env.local created with IP: $LOCAL_IP"

# Pass extra args to expo (e.g., -c for clear cache)
npx expo start --tunnel "$@"
