-- Restore premium fields that were incorrectly dropped by 20260321124429_remote_schema.sql
-- That migration was generated by `supabase db pull` before the premium migrations were pushed to remote,
-- causing it to DROP columns that should exist.

ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS is_premium BOOLEAN DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS premium_plan_type TEXT CHECK (premium_plan_type IN ('monthly', 'yearly')),
  ADD COLUMN IF NOT EXISTS premium_expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS premium_purchase_token TEXT;
